Namespace = ""
NotaryGroupConfig = "../perfgroup.toml"
PublicIP = ""
Port = 0
WebSocketPort = 0
SecureWebSocketDomain = ""
CertificateCache = ""
BootstrapOnly = false
TracingSystem = ""

[Storage]
  Kind = ""
  Path = ""
  CacheSize = 0
  RegionEndpoint = ""
  Bucket = ""
  Region = ""
  AccessKey = ""
  SecretKey = ""
  LocalS3 = false
  RootDirectory = ""

[PrivateKeySet]
  SignKeyHex = "0x643a3efac00c99da64d0cc0365c04feadd3685d2e4b4a4d8d794898df02dcd70"
  DestKeyHex = "0x0f4355c931fcd36d2b0c206353210566f98d1a0e67bf959d251b46aa322d1676"
