tupelos:
  local:
    docker-compose: true

testers:
  js-sdk-latest:
    image: quorumcontrol/tupelo-js-sdk:latest
    command: ["npx", "mocha", "--exit"]
  js-sdk-master:
    image: quorumcontrol/tupelo-js-sdk:master
    command: ["npx", "mocha", "--exit"]
  go-sdk-latest:
    image: quorumcontrol/tupelo-go-sdk:latest
    command: ["go", "test", "-mod=vendor", "-tags=integration", "-timeout=2m", "./..."]
  go-sdk-master:
    image: quorumcontrol/tupelo-go-sdk:master
    command: ["go", "test", "-mod=vendor", "-tags=integration", "-timeout=2m", "./..."]
