version: 0.2

env:
  parameter-store:
    SSH_KEY: "/codebuild/qc-build-bot-rsa"

phases:
  build:
    commands:
      - docker run -w /app -e SSH_KEY -v $(pwd):/app golang:1.12 ./scripts/build-within-docker.sh
