version: "3"
services:
  benchmark:
    build: .
    volumes:
      - ./docker/configs/localperftest:/configs
    command: ["-L", "info", "benchmark", "--config", "/configs/benchmark/config.toml", "--fault-detector", "--delay", "15", "-c", "50", "-d", "15", "-t", "20"]
