version: "3"
services:
  benchmark:
    build: .
    volumes:
      - ./docker/configs/localdocker:/configs
    command: ["-L", "debug", "benchmark", "--config", "/configs/benchmark/config.toml", "--delay", "15", "-c", "50", "-d", "15", "-t", "20"]
