version: "3"
services:
  benchmark:
    build: .
    volumes:
      - ./configs/localperftest:/configs
    command: ["-L", "info", "benchmark", "--config", "/configs/benchmark/config.toml", "--delay", "15", "-c", "40", "-d", "15", "-t", "20"]
