version: "3"
services:
  bootstrap:
    environment:
      ELASTIC_APM_SERVER_URL: "http://apmserver:8200"
      TRACING_ENABLED: "true"
  node0:
    environment:
      ELASTIC_APM_SERVER_URL: "http://apmserver:8200"
      TRACING_ENABLED: "true"
  node1:
    environment:
      ELASTIC_APM_SERVER_URL: "http://apmserver:8200"
      TRACING_ENABLED: "true"
  node2:
    environment:
      ELASTIC_APM_SERVER_URL: "http://apmserver:8200"
      TRACING_ENABLED: "true"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    ports:
      - 9200
    environment:
      discovery.type: single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.3
    ports:
      - 5601:5601
    command:
      - kibana-docker
      - -e
      - http://elasticsearch:9200
  apmserver:
    image: docker.elastic.co/apm/apm-server:6.5.3
    command:
      - apm-server
      - -E
      - output.elasticsearch.hosts=["http://elasticsearch:9200"]