// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Credentials struct {
	WalletName           string   `protobuf:"bytes,1,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
	PassPhrase           string   `protobuf:"bytes,2,opt,name=pass_phrase,json=passPhrase,proto3" json:"pass_phrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{0}
}
func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (dst *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(dst, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetWalletName() string {
	if m != nil {
		return m.WalletName
	}
	return ""
}

func (m *Credentials) GetPassPhrase() string {
	if m != nil {
		return m.PassPhrase
	}
	return ""
}

type SerializableSignature struct {
	Signers              []bool   `protobuf:"varint,1,rep,packed,name=signers,proto3" json:"signers,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SerializableSignature) Reset()         { *m = SerializableSignature{} }
func (m *SerializableSignature) String() string { return proto.CompactTextString(m) }
func (*SerializableSignature) ProtoMessage()    {}
func (*SerializableSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{1}
}
func (m *SerializableSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerializableSignature.Unmarshal(m, b)
}
func (m *SerializableSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerializableSignature.Marshal(b, m, deterministic)
}
func (dst *SerializableSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerializableSignature.Merge(dst, src)
}
func (m *SerializableSignature) XXX_Size() int {
	return xxx_messageInfo_SerializableSignature.Size(m)
}
func (m *SerializableSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_SerializableSignature.DiscardUnknown(m)
}

var xxx_messageInfo_SerializableSignature proto.InternalMessageInfo

func (m *SerializableSignature) GetSigners() []bool {
	if m != nil {
		return m.Signers
	}
	return nil
}

func (m *SerializableSignature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SerializableSignature) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type SerializableChainTree struct {
	Dag                  [][]byte                          `protobuf:"bytes,1,rep,name=dag,proto3" json:"dag,omitempty"`
	Signatures           map[string]*SerializableSignature `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *SerializableChainTree) Reset()         { *m = SerializableChainTree{} }
func (m *SerializableChainTree) String() string { return proto.CompactTextString(m) }
func (*SerializableChainTree) ProtoMessage()    {}
func (*SerializableChainTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{2}
}
func (m *SerializableChainTree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerializableChainTree.Unmarshal(m, b)
}
func (m *SerializableChainTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerializableChainTree.Marshal(b, m, deterministic)
}
func (dst *SerializableChainTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerializableChainTree.Merge(dst, src)
}
func (m *SerializableChainTree) XXX_Size() int {
	return xxx_messageInfo_SerializableChainTree.Size(m)
}
func (m *SerializableChainTree) XXX_DiscardUnknown() {
	xxx_messageInfo_SerializableChainTree.DiscardUnknown(m)
}

var xxx_messageInfo_SerializableChainTree proto.InternalMessageInfo

func (m *SerializableChainTree) GetDag() [][]byte {
	if m != nil {
		return m.Dag
	}
	return nil
}

func (m *SerializableChainTree) GetSignatures() map[string]*SerializableSignature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

type RegisterWalletRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegisterWalletRequest) Reset()         { *m = RegisterWalletRequest{} }
func (m *RegisterWalletRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterWalletRequest) ProtoMessage()    {}
func (*RegisterWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{3}
}
func (m *RegisterWalletRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterWalletRequest.Unmarshal(m, b)
}
func (m *RegisterWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterWalletRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterWalletRequest.Merge(dst, src)
}
func (m *RegisterWalletRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterWalletRequest.Size(m)
}
func (m *RegisterWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterWalletRequest proto.InternalMessageInfo

func (m *RegisterWalletRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

type RegisterWalletResponse struct {
	WalletName           string   `protobuf:"bytes,1,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterWalletResponse) Reset()         { *m = RegisterWalletResponse{} }
func (m *RegisterWalletResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterWalletResponse) ProtoMessage()    {}
func (*RegisterWalletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{4}
}
func (m *RegisterWalletResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterWalletResponse.Unmarshal(m, b)
}
func (m *RegisterWalletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterWalletResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterWalletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterWalletResponse.Merge(dst, src)
}
func (m *RegisterWalletResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterWalletResponse.Size(m)
}
func (m *RegisterWalletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterWalletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterWalletResponse proto.InternalMessageInfo

func (m *RegisterWalletResponse) GetWalletName() string {
	if m != nil {
		return m.WalletName
	}
	return ""
}

type GenerateChainRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	KeyAddr              string       `protobuf:"bytes,2,opt,name=key_addr,json=keyAddr,proto3" json:"key_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GenerateChainRequest) Reset()         { *m = GenerateChainRequest{} }
func (m *GenerateChainRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateChainRequest) ProtoMessage()    {}
func (*GenerateChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{5}
}
func (m *GenerateChainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateChainRequest.Unmarshal(m, b)
}
func (m *GenerateChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateChainRequest.Marshal(b, m, deterministic)
}
func (dst *GenerateChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateChainRequest.Merge(dst, src)
}
func (m *GenerateChainRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateChainRequest.Size(m)
}
func (m *GenerateChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateChainRequest proto.InternalMessageInfo

func (m *GenerateChainRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

func (m *GenerateChainRequest) GetKeyAddr() string {
	if m != nil {
		return m.KeyAddr
	}
	return ""
}

type GenerateChainResponse struct {
	ChainId              string   `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateChainResponse) Reset()         { *m = GenerateChainResponse{} }
func (m *GenerateChainResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateChainResponse) ProtoMessage()    {}
func (*GenerateChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{6}
}
func (m *GenerateChainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateChainResponse.Unmarshal(m, b)
}
func (m *GenerateChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateChainResponse.Marshal(b, m, deterministic)
}
func (dst *GenerateChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateChainResponse.Merge(dst, src)
}
func (m *GenerateChainResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateChainResponse.Size(m)
}
func (m *GenerateChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateChainResponse proto.InternalMessageInfo

func (m *GenerateChainResponse) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

type ExportChainRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	ChainId              string       `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ExportChainRequest) Reset()         { *m = ExportChainRequest{} }
func (m *ExportChainRequest) String() string { return proto.CompactTextString(m) }
func (*ExportChainRequest) ProtoMessage()    {}
func (*ExportChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{7}
}
func (m *ExportChainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportChainRequest.Unmarshal(m, b)
}
func (m *ExportChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportChainRequest.Marshal(b, m, deterministic)
}
func (dst *ExportChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportChainRequest.Merge(dst, src)
}
func (m *ExportChainRequest) XXX_Size() int {
	return xxx_messageInfo_ExportChainRequest.Size(m)
}
func (m *ExportChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExportChainRequest proto.InternalMessageInfo

func (m *ExportChainRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

func (m *ExportChainRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

type ExportChainResponse struct {
	ChainTree            string   `protobuf:"bytes,1,opt,name=chain_tree,json=chainTree,proto3" json:"chain_tree,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExportChainResponse) Reset()         { *m = ExportChainResponse{} }
func (m *ExportChainResponse) String() string { return proto.CompactTextString(m) }
func (*ExportChainResponse) ProtoMessage()    {}
func (*ExportChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{8}
}
func (m *ExportChainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportChainResponse.Unmarshal(m, b)
}
func (m *ExportChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportChainResponse.Marshal(b, m, deterministic)
}
func (dst *ExportChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportChainResponse.Merge(dst, src)
}
func (m *ExportChainResponse) XXX_Size() int {
	return xxx_messageInfo_ExportChainResponse.Size(m)
}
func (m *ExportChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExportChainResponse proto.InternalMessageInfo

func (m *ExportChainResponse) GetChainTree() string {
	if m != nil {
		return m.ChainTree
	}
	return ""
}

type ImportChainRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	KeyAddr              string       `protobuf:"bytes,2,opt,name=key_addr,json=keyAddr,proto3" json:"key_addr,omitempty"`
	ChainTree            string       `protobuf:"bytes,3,opt,name=chain_tree,json=chainTree,proto3" json:"chain_tree,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ImportChainRequest) Reset()         { *m = ImportChainRequest{} }
func (m *ImportChainRequest) String() string { return proto.CompactTextString(m) }
func (*ImportChainRequest) ProtoMessage()    {}
func (*ImportChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{9}
}
func (m *ImportChainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportChainRequest.Unmarshal(m, b)
}
func (m *ImportChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportChainRequest.Marshal(b, m, deterministic)
}
func (dst *ImportChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportChainRequest.Merge(dst, src)
}
func (m *ImportChainRequest) XXX_Size() int {
	return xxx_messageInfo_ImportChainRequest.Size(m)
}
func (m *ImportChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImportChainRequest proto.InternalMessageInfo

func (m *ImportChainRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

func (m *ImportChainRequest) GetKeyAddr() string {
	if m != nil {
		return m.KeyAddr
	}
	return ""
}

func (m *ImportChainRequest) GetChainTree() string {
	if m != nil {
		return m.ChainTree
	}
	return ""
}

type ImportChainResponse struct {
	ChainId              string   `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportChainResponse) Reset()         { *m = ImportChainResponse{} }
func (m *ImportChainResponse) String() string { return proto.CompactTextString(m) }
func (*ImportChainResponse) ProtoMessage()    {}
func (*ImportChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{10}
}
func (m *ImportChainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportChainResponse.Unmarshal(m, b)
}
func (m *ImportChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportChainResponse.Marshal(b, m, deterministic)
}
func (dst *ImportChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportChainResponse.Merge(dst, src)
}
func (m *ImportChainResponse) XXX_Size() int {
	return xxx_messageInfo_ImportChainResponse.Size(m)
}
func (m *ImportChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImportChainResponse proto.InternalMessageInfo

func (m *ImportChainResponse) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

type GenerateKeyRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GenerateKeyRequest) Reset()         { *m = GenerateKeyRequest{} }
func (m *GenerateKeyRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateKeyRequest) ProtoMessage()    {}
func (*GenerateKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{11}
}
func (m *GenerateKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateKeyRequest.Unmarshal(m, b)
}
func (m *GenerateKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateKeyRequest.Marshal(b, m, deterministic)
}
func (dst *GenerateKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateKeyRequest.Merge(dst, src)
}
func (m *GenerateKeyRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateKeyRequest.Size(m)
}
func (m *GenerateKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateKeyRequest proto.InternalMessageInfo

func (m *GenerateKeyRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

type GenerateKeyResponse struct {
	KeyAddr              string   `protobuf:"bytes,1,opt,name=key_addr,json=keyAddr,proto3" json:"key_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateKeyResponse) Reset()         { *m = GenerateKeyResponse{} }
func (m *GenerateKeyResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateKeyResponse) ProtoMessage()    {}
func (*GenerateKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{12}
}
func (m *GenerateKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateKeyResponse.Unmarshal(m, b)
}
func (m *GenerateKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateKeyResponse.Marshal(b, m, deterministic)
}
func (dst *GenerateKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateKeyResponse.Merge(dst, src)
}
func (m *GenerateKeyResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateKeyResponse.Size(m)
}
func (m *GenerateKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateKeyResponse proto.InternalMessageInfo

func (m *GenerateKeyResponse) GetKeyAddr() string {
	if m != nil {
		return m.KeyAddr
	}
	return ""
}

type GetTipRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	ChainId              string       `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetTipRequest) Reset()         { *m = GetTipRequest{} }
func (m *GetTipRequest) String() string { return proto.CompactTextString(m) }
func (*GetTipRequest) ProtoMessage()    {}
func (*GetTipRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{13}
}
func (m *GetTipRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTipRequest.Unmarshal(m, b)
}
func (m *GetTipRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTipRequest.Marshal(b, m, deterministic)
}
func (dst *GetTipRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTipRequest.Merge(dst, src)
}
func (m *GetTipRequest) XXX_Size() int {
	return xxx_messageInfo_GetTipRequest.Size(m)
}
func (m *GetTipRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTipRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTipRequest proto.InternalMessageInfo

func (m *GetTipRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

func (m *GetTipRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

type GetTipResponse struct {
	Tip                  string   `protobuf:"bytes,1,opt,name=tip,proto3" json:"tip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTipResponse) Reset()         { *m = GetTipResponse{} }
func (m *GetTipResponse) String() string { return proto.CompactTextString(m) }
func (*GetTipResponse) ProtoMessage()    {}
func (*GetTipResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{14}
}
func (m *GetTipResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTipResponse.Unmarshal(m, b)
}
func (m *GetTipResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTipResponse.Marshal(b, m, deterministic)
}
func (dst *GetTipResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTipResponse.Merge(dst, src)
}
func (m *GetTipResponse) XXX_Size() int {
	return xxx_messageInfo_GetTipResponse.Size(m)
}
func (m *GetTipResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTipResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTipResponse proto.InternalMessageInfo

func (m *GetTipResponse) GetTip() string {
	if m != nil {
		return m.Tip
	}
	return ""
}

type ListChainIdsRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListChainIdsRequest) Reset()         { *m = ListChainIdsRequest{} }
func (m *ListChainIdsRequest) String() string { return proto.CompactTextString(m) }
func (*ListChainIdsRequest) ProtoMessage()    {}
func (*ListChainIdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{15}
}
func (m *ListChainIdsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListChainIdsRequest.Unmarshal(m, b)
}
func (m *ListChainIdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListChainIdsRequest.Marshal(b, m, deterministic)
}
func (dst *ListChainIdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListChainIdsRequest.Merge(dst, src)
}
func (m *ListChainIdsRequest) XXX_Size() int {
	return xxx_messageInfo_ListChainIdsRequest.Size(m)
}
func (m *ListChainIdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListChainIdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListChainIdsRequest proto.InternalMessageInfo

func (m *ListChainIdsRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

type ListChainIdsResponse struct {
	ChainIds             []string `protobuf:"bytes,1,rep,name=chain_ids,json=chainIds,proto3" json:"chain_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListChainIdsResponse) Reset()         { *m = ListChainIdsResponse{} }
func (m *ListChainIdsResponse) String() string { return proto.CompactTextString(m) }
func (*ListChainIdsResponse) ProtoMessage()    {}
func (*ListChainIdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{16}
}
func (m *ListChainIdsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListChainIdsResponse.Unmarshal(m, b)
}
func (m *ListChainIdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListChainIdsResponse.Marshal(b, m, deterministic)
}
func (dst *ListChainIdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListChainIdsResponse.Merge(dst, src)
}
func (m *ListChainIdsResponse) XXX_Size() int {
	return xxx_messageInfo_ListChainIdsResponse.Size(m)
}
func (m *ListChainIdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListChainIdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListChainIdsResponse proto.InternalMessageInfo

func (m *ListChainIdsResponse) GetChainIds() []string {
	if m != nil {
		return m.ChainIds
	}
	return nil
}

type ListKeysRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListKeysRequest) Reset()         { *m = ListKeysRequest{} }
func (m *ListKeysRequest) String() string { return proto.CompactTextString(m) }
func (*ListKeysRequest) ProtoMessage()    {}
func (*ListKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{17}
}
func (m *ListKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListKeysRequest.Unmarshal(m, b)
}
func (m *ListKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListKeysRequest.Marshal(b, m, deterministic)
}
func (dst *ListKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListKeysRequest.Merge(dst, src)
}
func (m *ListKeysRequest) XXX_Size() int {
	return xxx_messageInfo_ListKeysRequest.Size(m)
}
func (m *ListKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListKeysRequest proto.InternalMessageInfo

func (m *ListKeysRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

type ListKeysResponse struct {
	KeyAddrs             []string `protobuf:"bytes,1,rep,name=key_addrs,json=keyAddrs,proto3" json:"key_addrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListKeysResponse) Reset()         { *m = ListKeysResponse{} }
func (m *ListKeysResponse) String() string { return proto.CompactTextString(m) }
func (*ListKeysResponse) ProtoMessage()    {}
func (*ListKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{18}
}
func (m *ListKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListKeysResponse.Unmarshal(m, b)
}
func (m *ListKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListKeysResponse.Marshal(b, m, deterministic)
}
func (dst *ListKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListKeysResponse.Merge(dst, src)
}
func (m *ListKeysResponse) XXX_Size() int {
	return xxx_messageInfo_ListKeysResponse.Size(m)
}
func (m *ListKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListKeysResponse proto.InternalMessageInfo

func (m *ListKeysResponse) GetKeyAddrs() []string {
	if m != nil {
		return m.KeyAddrs
	}
	return nil
}

type SetOwnerRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	ChainId              string       `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	KeyAddr              string       `protobuf:"bytes,3,opt,name=key_addr,json=keyAddr,proto3" json:"key_addr,omitempty"`
	NewOwnerKeys         []string     `protobuf:"bytes,4,rep,name=new_owner_keys,json=newOwnerKeys,proto3" json:"new_owner_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SetOwnerRequest) Reset()         { *m = SetOwnerRequest{} }
func (m *SetOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*SetOwnerRequest) ProtoMessage()    {}
func (*SetOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{19}
}
func (m *SetOwnerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetOwnerRequest.Unmarshal(m, b)
}
func (m *SetOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetOwnerRequest.Marshal(b, m, deterministic)
}
func (dst *SetOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetOwnerRequest.Merge(dst, src)
}
func (m *SetOwnerRequest) XXX_Size() int {
	return xxx_messageInfo_SetOwnerRequest.Size(m)
}
func (m *SetOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetOwnerRequest proto.InternalMessageInfo

func (m *SetOwnerRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

func (m *SetOwnerRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *SetOwnerRequest) GetKeyAddr() string {
	if m != nil {
		return m.KeyAddr
	}
	return ""
}

func (m *SetOwnerRequest) GetNewOwnerKeys() []string {
	if m != nil {
		return m.NewOwnerKeys
	}
	return nil
}

type SetOwnerResponse struct {
	Tip                  string   `protobuf:"bytes,1,opt,name=tip,proto3" json:"tip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetOwnerResponse) Reset()         { *m = SetOwnerResponse{} }
func (m *SetOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*SetOwnerResponse) ProtoMessage()    {}
func (*SetOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{20}
}
func (m *SetOwnerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetOwnerResponse.Unmarshal(m, b)
}
func (m *SetOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetOwnerResponse.Marshal(b, m, deterministic)
}
func (dst *SetOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetOwnerResponse.Merge(dst, src)
}
func (m *SetOwnerResponse) XXX_Size() int {
	return xxx_messageInfo_SetOwnerResponse.Size(m)
}
func (m *SetOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetOwnerResponse proto.InternalMessageInfo

func (m *SetOwnerResponse) GetTip() string {
	if m != nil {
		return m.Tip
	}
	return ""
}

type SetDataRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	ChainId              string       `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	KeyAddr              string       `protobuf:"bytes,3,opt,name=key_addr,json=keyAddr,proto3" json:"key_addr,omitempty"`
	Path                 string       `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Value                []byte       `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SetDataRequest) Reset()         { *m = SetDataRequest{} }
func (m *SetDataRequest) String() string { return proto.CompactTextString(m) }
func (*SetDataRequest) ProtoMessage()    {}
func (*SetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{21}
}
func (m *SetDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDataRequest.Unmarshal(m, b)
}
func (m *SetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDataRequest.Marshal(b, m, deterministic)
}
func (dst *SetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDataRequest.Merge(dst, src)
}
func (m *SetDataRequest) XXX_Size() int {
	return xxx_messageInfo_SetDataRequest.Size(m)
}
func (m *SetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetDataRequest proto.InternalMessageInfo

func (m *SetDataRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

func (m *SetDataRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *SetDataRequest) GetKeyAddr() string {
	if m != nil {
		return m.KeyAddr
	}
	return ""
}

func (m *SetDataRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *SetDataRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SetDataResponse struct {
	Tip                  string   `protobuf:"bytes,1,opt,name=tip,proto3" json:"tip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDataResponse) Reset()         { *m = SetDataResponse{} }
func (m *SetDataResponse) String() string { return proto.CompactTextString(m) }
func (*SetDataResponse) ProtoMessage()    {}
func (*SetDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{22}
}
func (m *SetDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDataResponse.Unmarshal(m, b)
}
func (m *SetDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDataResponse.Marshal(b, m, deterministic)
}
func (dst *SetDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDataResponse.Merge(dst, src)
}
func (m *SetDataResponse) XXX_Size() int {
	return xxx_messageInfo_SetDataResponse.Size(m)
}
func (m *SetDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetDataResponse proto.InternalMessageInfo

func (m *SetDataResponse) GetTip() string {
	if m != nil {
		return m.Tip
	}
	return ""
}

type ResolveRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	ChainId              string       `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Path                 string       `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ResolveRequest) Reset()         { *m = ResolveRequest{} }
func (m *ResolveRequest) String() string { return proto.CompactTextString(m) }
func (*ResolveRequest) ProtoMessage()    {}
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{23}
}
func (m *ResolveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveRequest.Unmarshal(m, b)
}
func (m *ResolveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveRequest.Marshal(b, m, deterministic)
}
func (dst *ResolveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveRequest.Merge(dst, src)
}
func (m *ResolveRequest) XXX_Size() int {
	return xxx_messageInfo_ResolveRequest.Size(m)
}
func (m *ResolveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveRequest proto.InternalMessageInfo

func (m *ResolveRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

func (m *ResolveRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *ResolveRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ResolveResponse struct {
	RemainingPath        string   `protobuf:"bytes,1,opt,name=remaining_path,json=remainingPath,proto3" json:"remaining_path,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolveResponse) Reset()         { *m = ResolveResponse{} }
func (m *ResolveResponse) String() string { return proto.CompactTextString(m) }
func (*ResolveResponse) ProtoMessage()    {}
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{24}
}
func (m *ResolveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveResponse.Unmarshal(m, b)
}
func (m *ResolveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveResponse.Marshal(b, m, deterministic)
}
func (dst *ResolveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveResponse.Merge(dst, src)
}
func (m *ResolveResponse) XXX_Size() int {
	return xxx_messageInfo_ResolveResponse.Size(m)
}
func (m *ResolveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveResponse proto.InternalMessageInfo

func (m *ResolveResponse) GetRemainingPath() string {
	if m != nil {
		return m.RemainingPath
	}
	return ""
}

func (m *ResolveResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type EstablishCoinRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	ChainId              string       `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	KeyAddr              string       `protobuf:"bytes,3,opt,name=key_addr,json=keyAddr,proto3" json:"key_addr,omitempty"`
	CoinName             string       `protobuf:"bytes,4,opt,name=coin_name,json=coinName,proto3" json:"coin_name,omitempty"`
	Maximum              uint64       `protobuf:"varint,5,opt,name=maximum,proto3" json:"maximum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EstablishCoinRequest) Reset()         { *m = EstablishCoinRequest{} }
func (m *EstablishCoinRequest) String() string { return proto.CompactTextString(m) }
func (*EstablishCoinRequest) ProtoMessage()    {}
func (*EstablishCoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{25}
}
func (m *EstablishCoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstablishCoinRequest.Unmarshal(m, b)
}
func (m *EstablishCoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstablishCoinRequest.Marshal(b, m, deterministic)
}
func (dst *EstablishCoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstablishCoinRequest.Merge(dst, src)
}
func (m *EstablishCoinRequest) XXX_Size() int {
	return xxx_messageInfo_EstablishCoinRequest.Size(m)
}
func (m *EstablishCoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EstablishCoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EstablishCoinRequest proto.InternalMessageInfo

func (m *EstablishCoinRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

func (m *EstablishCoinRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *EstablishCoinRequest) GetKeyAddr() string {
	if m != nil {
		return m.KeyAddr
	}
	return ""
}

func (m *EstablishCoinRequest) GetCoinName() string {
	if m != nil {
		return m.CoinName
	}
	return ""
}

func (m *EstablishCoinRequest) GetMaximum() uint64 {
	if m != nil {
		return m.Maximum
	}
	return 0
}

type EstablishCoinResponse struct {
	Tip                  string   `protobuf:"bytes,1,opt,name=tip,proto3" json:"tip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EstablishCoinResponse) Reset()         { *m = EstablishCoinResponse{} }
func (m *EstablishCoinResponse) String() string { return proto.CompactTextString(m) }
func (*EstablishCoinResponse) ProtoMessage()    {}
func (*EstablishCoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{26}
}
func (m *EstablishCoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstablishCoinResponse.Unmarshal(m, b)
}
func (m *EstablishCoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstablishCoinResponse.Marshal(b, m, deterministic)
}
func (dst *EstablishCoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstablishCoinResponse.Merge(dst, src)
}
func (m *EstablishCoinResponse) XXX_Size() int {
	return xxx_messageInfo_EstablishCoinResponse.Size(m)
}
func (m *EstablishCoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EstablishCoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EstablishCoinResponse proto.InternalMessageInfo

func (m *EstablishCoinResponse) GetTip() string {
	if m != nil {
		return m.Tip
	}
	return ""
}

type MintCoinRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	ChainId              string       `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	KeyAddr              string       `protobuf:"bytes,3,opt,name=key_addr,json=keyAddr,proto3" json:"key_addr,omitempty"`
	CoinName             string       `protobuf:"bytes,4,opt,name=coin_name,json=coinName,proto3" json:"coin_name,omitempty"`
	Amount               uint64       `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MintCoinRequest) Reset()         { *m = MintCoinRequest{} }
func (m *MintCoinRequest) String() string { return proto.CompactTextString(m) }
func (*MintCoinRequest) ProtoMessage()    {}
func (*MintCoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{27}
}
func (m *MintCoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MintCoinRequest.Unmarshal(m, b)
}
func (m *MintCoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MintCoinRequest.Marshal(b, m, deterministic)
}
func (dst *MintCoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintCoinRequest.Merge(dst, src)
}
func (m *MintCoinRequest) XXX_Size() int {
	return xxx_messageInfo_MintCoinRequest.Size(m)
}
func (m *MintCoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MintCoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MintCoinRequest proto.InternalMessageInfo

func (m *MintCoinRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

func (m *MintCoinRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *MintCoinRequest) GetKeyAddr() string {
	if m != nil {
		return m.KeyAddr
	}
	return ""
}

func (m *MintCoinRequest) GetCoinName() string {
	if m != nil {
		return m.CoinName
	}
	return ""
}

func (m *MintCoinRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type MintCoinResponse struct {
	Tip                  string   `protobuf:"bytes,1,opt,name=tip,proto3" json:"tip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MintCoinResponse) Reset()         { *m = MintCoinResponse{} }
func (m *MintCoinResponse) String() string { return proto.CompactTextString(m) }
func (*MintCoinResponse) ProtoMessage()    {}
func (*MintCoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_982042c875d0a9f3, []int{28}
}
func (m *MintCoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MintCoinResponse.Unmarshal(m, b)
}
func (m *MintCoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MintCoinResponse.Marshal(b, m, deterministic)
}
func (dst *MintCoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintCoinResponse.Merge(dst, src)
}
func (m *MintCoinResponse) XXX_Size() int {
	return xxx_messageInfo_MintCoinResponse.Size(m)
}
func (m *MintCoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MintCoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MintCoinResponse proto.InternalMessageInfo

func (m *MintCoinResponse) GetTip() string {
	if m != nil {
		return m.Tip
	}
	return ""
}

func init() {
	proto.RegisterType((*Credentials)(nil), "walletrpc.Credentials")
	proto.RegisterType((*SerializableSignature)(nil), "walletrpc.SerializableSignature")
	proto.RegisterType((*SerializableChainTree)(nil), "walletrpc.SerializableChainTree")
	proto.RegisterMapType((map[string]*SerializableSignature)(nil), "walletrpc.SerializableChainTree.SignaturesEntry")
	proto.RegisterType((*RegisterWalletRequest)(nil), "walletrpc.RegisterWalletRequest")
	proto.RegisterType((*RegisterWalletResponse)(nil), "walletrpc.RegisterWalletResponse")
	proto.RegisterType((*GenerateChainRequest)(nil), "walletrpc.GenerateChainRequest")
	proto.RegisterType((*GenerateChainResponse)(nil), "walletrpc.GenerateChainResponse")
	proto.RegisterType((*ExportChainRequest)(nil), "walletrpc.ExportChainRequest")
	proto.RegisterType((*ExportChainResponse)(nil), "walletrpc.ExportChainResponse")
	proto.RegisterType((*ImportChainRequest)(nil), "walletrpc.ImportChainRequest")
	proto.RegisterType((*ImportChainResponse)(nil), "walletrpc.ImportChainResponse")
	proto.RegisterType((*GenerateKeyRequest)(nil), "walletrpc.GenerateKeyRequest")
	proto.RegisterType((*GenerateKeyResponse)(nil), "walletrpc.GenerateKeyResponse")
	proto.RegisterType((*GetTipRequest)(nil), "walletrpc.GetTipRequest")
	proto.RegisterType((*GetTipResponse)(nil), "walletrpc.GetTipResponse")
	proto.RegisterType((*ListChainIdsRequest)(nil), "walletrpc.ListChainIdsRequest")
	proto.RegisterType((*ListChainIdsResponse)(nil), "walletrpc.ListChainIdsResponse")
	proto.RegisterType((*ListKeysRequest)(nil), "walletrpc.ListKeysRequest")
	proto.RegisterType((*ListKeysResponse)(nil), "walletrpc.ListKeysResponse")
	proto.RegisterType((*SetOwnerRequest)(nil), "walletrpc.SetOwnerRequest")
	proto.RegisterType((*SetOwnerResponse)(nil), "walletrpc.SetOwnerResponse")
	proto.RegisterType((*SetDataRequest)(nil), "walletrpc.SetDataRequest")
	proto.RegisterType((*SetDataResponse)(nil), "walletrpc.SetDataResponse")
	proto.RegisterType((*ResolveRequest)(nil), "walletrpc.ResolveRequest")
	proto.RegisterType((*ResolveResponse)(nil), "walletrpc.ResolveResponse")
	proto.RegisterType((*EstablishCoinRequest)(nil), "walletrpc.EstablishCoinRequest")
	proto.RegisterType((*EstablishCoinResponse)(nil), "walletrpc.EstablishCoinResponse")
	proto.RegisterType((*MintCoinRequest)(nil), "walletrpc.MintCoinRequest")
	proto.RegisterType((*MintCoinResponse)(nil), "walletrpc.MintCoinResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WalletRPCServiceClient is the client API for WalletRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletRPCServiceClient interface {
	Register(ctx context.Context, in *RegisterWalletRequest, opts ...grpc.CallOption) (*RegisterWalletResponse, error)
	GenerateKey(ctx context.Context, in *GenerateKeyRequest, opts ...grpc.CallOption) (*GenerateKeyResponse, error)
	CreateChainTree(ctx context.Context, in *GenerateChainRequest, opts ...grpc.CallOption) (*GenerateChainResponse, error)
	ExportChainTree(ctx context.Context, in *ExportChainRequest, opts ...grpc.CallOption) (*ExportChainResponse, error)
	ImportChainTree(ctx context.Context, in *ImportChainRequest, opts ...grpc.CallOption) (*ImportChainResponse, error)
	GetTip(ctx context.Context, in *GetTipRequest, opts ...grpc.CallOption) (*GetTipResponse, error)
	ListChainIds(ctx context.Context, in *ListChainIdsRequest, opts ...grpc.CallOption) (*ListChainIdsResponse, error)
	ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error)
	SetOwner(ctx context.Context, in *SetOwnerRequest, opts ...grpc.CallOption) (*SetOwnerResponse, error)
	SetData(ctx context.Context, in *SetDataRequest, opts ...grpc.CallOption) (*SetDataResponse, error)
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
	EstablishCoin(ctx context.Context, in *EstablishCoinRequest, opts ...grpc.CallOption) (*EstablishCoinResponse, error)
	MintCoin(ctx context.Context, in *MintCoinRequest, opts ...grpc.CallOption) (*MintCoinResponse, error)
}

type walletRPCServiceClient struct {
	cc *grpc.ClientConn
}

func NewWalletRPCServiceClient(cc *grpc.ClientConn) WalletRPCServiceClient {
	return &walletRPCServiceClient{cc}
}

func (c *walletRPCServiceClient) Register(ctx context.Context, in *RegisterWalletRequest, opts ...grpc.CallOption) (*RegisterWalletResponse, error) {
	out := new(RegisterWalletResponse)
	err := c.cc.Invoke(ctx, "/walletrpc.WalletRPCService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) GenerateKey(ctx context.Context, in *GenerateKeyRequest, opts ...grpc.CallOption) (*GenerateKeyResponse, error) {
	out := new(GenerateKeyResponse)
	err := c.cc.Invoke(ctx, "/walletrpc.WalletRPCService/GenerateKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) CreateChainTree(ctx context.Context, in *GenerateChainRequest, opts ...grpc.CallOption) (*GenerateChainResponse, error) {
	out := new(GenerateChainResponse)
	err := c.cc.Invoke(ctx, "/walletrpc.WalletRPCService/CreateChainTree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) ExportChainTree(ctx context.Context, in *ExportChainRequest, opts ...grpc.CallOption) (*ExportChainResponse, error) {
	out := new(ExportChainResponse)
	err := c.cc.Invoke(ctx, "/walletrpc.WalletRPCService/ExportChainTree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) ImportChainTree(ctx context.Context, in *ImportChainRequest, opts ...grpc.CallOption) (*ImportChainResponse, error) {
	out := new(ImportChainResponse)
	err := c.cc.Invoke(ctx, "/walletrpc.WalletRPCService/ImportChainTree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) GetTip(ctx context.Context, in *GetTipRequest, opts ...grpc.CallOption) (*GetTipResponse, error) {
	out := new(GetTipResponse)
	err := c.cc.Invoke(ctx, "/walletrpc.WalletRPCService/GetTip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) ListChainIds(ctx context.Context, in *ListChainIdsRequest, opts ...grpc.CallOption) (*ListChainIdsResponse, error) {
	out := new(ListChainIdsResponse)
	err := c.cc.Invoke(ctx, "/walletrpc.WalletRPCService/ListChainIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error) {
	out := new(ListKeysResponse)
	err := c.cc.Invoke(ctx, "/walletrpc.WalletRPCService/ListKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) SetOwner(ctx context.Context, in *SetOwnerRequest, opts ...grpc.CallOption) (*SetOwnerResponse, error) {
	out := new(SetOwnerResponse)
	err := c.cc.Invoke(ctx, "/walletrpc.WalletRPCService/SetOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) SetData(ctx context.Context, in *SetDataRequest, opts ...grpc.CallOption) (*SetDataResponse, error) {
	out := new(SetDataResponse)
	err := c.cc.Invoke(ctx, "/walletrpc.WalletRPCService/SetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	out := new(ResolveResponse)
	err := c.cc.Invoke(ctx, "/walletrpc.WalletRPCService/Resolve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) EstablishCoin(ctx context.Context, in *EstablishCoinRequest, opts ...grpc.CallOption) (*EstablishCoinResponse, error) {
	out := new(EstablishCoinResponse)
	err := c.cc.Invoke(ctx, "/walletrpc.WalletRPCService/EstablishCoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) MintCoin(ctx context.Context, in *MintCoinRequest, opts ...grpc.CallOption) (*MintCoinResponse, error) {
	out := new(MintCoinResponse)
	err := c.cc.Invoke(ctx, "/walletrpc.WalletRPCService/MintCoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletRPCServiceServer is the server API for WalletRPCService service.
type WalletRPCServiceServer interface {
	Register(context.Context, *RegisterWalletRequest) (*RegisterWalletResponse, error)
	GenerateKey(context.Context, *GenerateKeyRequest) (*GenerateKeyResponse, error)
	CreateChainTree(context.Context, *GenerateChainRequest) (*GenerateChainResponse, error)
	ExportChainTree(context.Context, *ExportChainRequest) (*ExportChainResponse, error)
	ImportChainTree(context.Context, *ImportChainRequest) (*ImportChainResponse, error)
	GetTip(context.Context, *GetTipRequest) (*GetTipResponse, error)
	ListChainIds(context.Context, *ListChainIdsRequest) (*ListChainIdsResponse, error)
	ListKeys(context.Context, *ListKeysRequest) (*ListKeysResponse, error)
	SetOwner(context.Context, *SetOwnerRequest) (*SetOwnerResponse, error)
	SetData(context.Context, *SetDataRequest) (*SetDataResponse, error)
	Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error)
	EstablishCoin(context.Context, *EstablishCoinRequest) (*EstablishCoinResponse, error)
	MintCoin(context.Context, *MintCoinRequest) (*MintCoinResponse, error)
}

func RegisterWalletRPCServiceServer(s *grpc.Server, srv WalletRPCServiceServer) {
	s.RegisterService(&_WalletRPCService_serviceDesc, srv)
}

func _WalletRPCService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletrpc.WalletRPCService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).Register(ctx, req.(*RegisterWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_GenerateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).GenerateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletrpc.WalletRPCService/GenerateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).GenerateKey(ctx, req.(*GenerateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_CreateChainTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).CreateChainTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletrpc.WalletRPCService/CreateChainTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).CreateChainTree(ctx, req.(*GenerateChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_ExportChainTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).ExportChainTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletrpc.WalletRPCService/ExportChainTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).ExportChainTree(ctx, req.(*ExportChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_ImportChainTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).ImportChainTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletrpc.WalletRPCService/ImportChainTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).ImportChainTree(ctx, req.(*ImportChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_GetTip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).GetTip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletrpc.WalletRPCService/GetTip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).GetTip(ctx, req.(*GetTipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_ListChainIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChainIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).ListChainIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletrpc.WalletRPCService/ListChainIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).ListChainIds(ctx, req.(*ListChainIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_ListKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).ListKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletrpc.WalletRPCService/ListKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).ListKeys(ctx, req.(*ListKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_SetOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).SetOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletrpc.WalletRPCService/SetOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).SetOwner(ctx, req.(*SetOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_SetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).SetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletrpc.WalletRPCService/SetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).SetData(ctx, req.(*SetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletrpc.WalletRPCService/Resolve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_EstablishCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstablishCoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).EstablishCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletrpc.WalletRPCService/EstablishCoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).EstablishCoin(ctx, req.(*EstablishCoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_MintCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintCoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).MintCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletrpc.WalletRPCService/MintCoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).MintCoin(ctx, req.(*MintCoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalletRPCService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "walletrpc.WalletRPCService",
	HandlerType: (*WalletRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _WalletRPCService_Register_Handler,
		},
		{
			MethodName: "GenerateKey",
			Handler:    _WalletRPCService_GenerateKey_Handler,
		},
		{
			MethodName: "CreateChainTree",
			Handler:    _WalletRPCService_CreateChainTree_Handler,
		},
		{
			MethodName: "ExportChainTree",
			Handler:    _WalletRPCService_ExportChainTree_Handler,
		},
		{
			MethodName: "ImportChainTree",
			Handler:    _WalletRPCService_ImportChainTree_Handler,
		},
		{
			MethodName: "GetTip",
			Handler:    _WalletRPCService_GetTip_Handler,
		},
		{
			MethodName: "ListChainIds",
			Handler:    _WalletRPCService_ListChainIds_Handler,
		},
		{
			MethodName: "ListKeys",
			Handler:    _WalletRPCService_ListKeys_Handler,
		},
		{
			MethodName: "SetOwner",
			Handler:    _WalletRPCService_SetOwner_Handler,
		},
		{
			MethodName: "SetData",
			Handler:    _WalletRPCService_SetData_Handler,
		},
		{
			MethodName: "Resolve",
			Handler:    _WalletRPCService_Resolve_Handler,
		},
		{
			MethodName: "EstablishCoin",
			Handler:    _WalletRPCService_EstablishCoin_Handler,
		},
		{
			MethodName: "MintCoin",
			Handler:    _WalletRPCService_MintCoin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_982042c875d0a9f3) }

var fileDescriptor_service_982042c875d0a9f3 = []byte{
	// 1005 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xff, 0x6b, 0x23, 0x45,
	0x14, 0x67, 0x9b, 0xf4, 0x92, 0xbc, 0xb4, 0x49, 0x98, 0x7e, 0x61, 0xbb, 0xe7, 0xd9, 0xb8, 0x9e,
	0x50, 0x41, 0x6a, 0xc9, 0x89, 0xa8, 0x20, 0xea, 0xc5, 0x72, 0x94, 0xab, 0x36, 0x6c, 0x0a, 0x8a,
	0x20, 0x61, 0x9a, 0x7d, 0xa4, 0x43, 0x93, 0xcd, 0x3a, 0x33, 0x69, 0x2f, 0xe2, 0x7f, 0x22, 0xf8,
	0x07, 0xf8, 0x9b, 0xff, 0x8f, 0x3f, 0xf9, 0x97, 0xc8, 0xce, 0xcc, 0x26, 0x3b, 0x9b, 0xcd, 0x1d,
	0xf4, 0x8a, 0xf8, 0xdb, 0xce, 0xb7, 0xcf, 0xfb, 0xbc, 0xf7, 0x66, 0xde, 0xe7, 0x2d, 0x6c, 0x0b,
	0xe4, 0xb7, 0x6c, 0x88, 0xc7, 0x31, 0x9f, 0xca, 0x29, 0xa9, 0xdd, 0xd1, 0xf1, 0x18, 0x25, 0x8f,
	0x87, 0xfe, 0x05, 0xd4, 0xbb, 0x1c, 0x43, 0x8c, 0x24, 0xa3, 0x63, 0x41, 0x0e, 0xa1, 0xae, 0xd7,
	0x06, 0x11, 0x9d, 0xa0, 0xeb, 0xb4, 0x9d, 0xa3, 0x5a, 0x00, 0x7a, 0xea, 0x7b, 0x3a, 0xc1, 0x64,
	0x43, 0x4c, 0x85, 0x18, 0xc4, 0xd7, 0x9c, 0x0a, 0x74, 0x37, 0xf4, 0x86, 0x64, 0xaa, 0xa7, 0x66,
	0xfc, 0x21, 0xec, 0xf5, 0x91, 0x33, 0x3a, 0x66, 0xbf, 0xd2, 0xab, 0x31, 0xf6, 0xd9, 0x28, 0xa2,
	0x72, 0xc6, 0x91, 0xb8, 0x50, 0x11, 0x6c, 0x14, 0x21, 0x17, 0xae, 0xd3, 0x2e, 0x1d, 0x55, 0x83,
	0x74, 0x48, 0xde, 0x81, 0x9a, 0x48, 0xb7, 0x29, 0xc4, 0xad, 0x60, 0x39, 0x41, 0x08, 0x94, 0xe5,
	0x3c, 0x46, 0xb7, 0xa4, 0x4c, 0xa9, 0x6f, 0xff, 0x6f, 0xc7, 0xb6, 0xd2, 0xbd, 0xa6, 0x2c, 0xba,
	0xe4, 0x88, 0xa4, 0x05, 0xa5, 0x90, 0x8e, 0x94, 0x85, 0xad, 0x20, 0xf9, 0x24, 0x3d, 0x80, 0x05,
	0x98, 0x70, 0x37, 0xda, 0xa5, 0xa3, 0x7a, 0xe7, 0xe4, 0x78, 0x11, 0x81, 0xe3, 0x42, 0x9c, 0xe3,
	0x05, 0x6f, 0x71, 0x1a, 0x49, 0x3e, 0x0f, 0x32, 0x18, 0xde, 0x00, 0x9a, 0xb9, 0xe5, 0xc4, 0xec,
	0x0d, 0xce, 0x4d, 0xbc, 0x92, 0x4f, 0xf2, 0x29, 0x6c, 0xde, 0xd2, 0xf1, 0x4c, 0x3b, 0x54, 0xef,
	0xb4, 0xd7, 0x58, 0x5c, 0x00, 0x05, 0x7a, 0xfb, 0x17, 0x1b, 0x9f, 0x39, 0xfe, 0x29, 0xec, 0x05,
	0x38, 0x62, 0x42, 0x22, 0xff, 0x41, 0x9d, 0x0a, 0xf0, 0x97, 0x19, 0x0a, 0x49, 0x3e, 0x82, 0xcd,
	0x21, 0xc7, 0x50, 0x28, 0x43, 0xf5, 0xce, 0x7e, 0x06, 0x34, 0x93, 0xc5, 0x40, 0x6f, 0xf2, 0x3f,
	0x87, 0xfd, 0x3c, 0x8c, 0x88, 0xa7, 0x91, 0xc0, 0x37, 0xa6, 0xd9, 0x1f, 0xc0, 0xee, 0x0b, 0x8c,
	0x90, 0x53, 0xa9, 0x63, 0x72, 0x2f, 0x02, 0xe4, 0x00, 0xaa, 0x37, 0x38, 0x1f, 0xd0, 0x30, 0xe4,
	0xe6, 0xa6, 0x54, 0x6e, 0x70, 0xfe, 0x4d, 0x18, 0x72, 0xbf, 0x03, 0x7b, 0x39, 0x03, 0x86, 0xda,
	0x01, 0x54, 0x87, 0xc9, 0xc4, 0x80, 0x85, 0x86, 0x57, 0x45, 0x8d, 0xcf, 0x42, 0xff, 0x67, 0x20,
	0xa7, 0xaf, 0xe2, 0x29, 0x97, 0x6f, 0x47, 0x69, 0x01, 0xbf, 0x61, 0xc3, 0x7f, 0x02, 0x3b, 0x16,
	0xbc, 0x21, 0xf4, 0x04, 0x40, 0x9f, 0x90, 0x1c, 0xd3, 0x50, 0xd5, 0x86, 0xe9, 0x45, 0xf1, 0x7f,
	0x03, 0x72, 0x36, 0x79, 0x7b, 0x52, 0x6b, 0xe2, 0x94, 0xb3, 0x5e, 0xca, 0x5b, 0x3f, 0x81, 0x1d,
	0xcb, 0xfa, 0x9b, 0x83, 0xf8, 0x1c, 0x48, 0x1a, 0xf8, 0x97, 0x38, 0xbf, 0xdf, 0xc5, 0x3a, 0x81,
	0x1d, 0x0b, 0x63, 0x69, 0x75, 0xe1, 0x86, 0x63, 0xa7, 0xfb, 0x47, 0xd8, 0x7e, 0x81, 0xf2, 0x92,
	0xc5, 0x0f, 0x9e, 0x35, 0x1f, 0x1a, 0x29, 0xb2, 0xa1, 0xd1, 0x82, 0x92, 0x64, 0x71, 0xfa, 0x16,
	0x25, 0x8b, 0xfd, 0x2e, 0xec, 0x9c, 0x33, 0xa1, 0x63, 0x74, 0x16, 0x8a, 0xfb, 0x39, 0xfd, 0x0c,
	0x76, 0x6d, 0x10, 0x63, 0xee, 0x31, 0xd4, 0x52, 0x6e, 0xba, 0xb2, 0xd5, 0x82, 0xaa, 0x21, 0x27,
	0xfc, 0xaf, 0xa0, 0x99, 0x1c, 0x7a, 0x89, 0xf3, 0x7b, 0x5a, 0xfd, 0x18, 0x5a, 0x4b, 0x80, 0xa5,
	0xc5, 0x34, 0xce, 0x0b, 0x8b, 0x26, 0xd0, 0xc2, 0xff, 0xdd, 0x81, 0x66, 0x1f, 0xe5, 0xc5, 0x5d,
	0x84, 0xfc, 0xa1, 0x83, 0x6d, 0x65, 0xb8, 0x64, 0x5f, 0xd4, 0xa7, 0xd0, 0x88, 0xf0, 0x6e, 0x30,
	0x4d, 0xec, 0x0e, 0x6e, 0x70, 0x2e, 0xdc, 0xb2, 0x62, 0xb6, 0x15, 0xe1, 0x9d, 0x22, 0x93, 0xb8,
	0xe0, 0x3f, 0x85, 0xd6, 0x92, 0xdc, 0xda, 0x7c, 0xfd, 0xe1, 0x40, 0xa3, 0x8f, 0xf2, 0x5b, 0x2a,
	0xe9, 0x7f, 0xe9, 0x02, 0x81, 0x72, 0x4c, 0xe5, 0xb5, 0x5b, 0xd6, 0x4a, 0x93, 0x7c, 0x93, 0xdd,
	0xb4, 0x8c, 0x6f, 0x2a, 0x5d, 0xd2, 0x03, 0xff, 0x7d, 0x15, 0x63, 0xcd, 0x6f, 0xad, 0x17, 0x13,
	0x68, 0x04, 0x28, 0xa6, 0xe3, 0x5b, 0x7c, 0x70, 0x27, 0x52, 0xa6, 0xa5, 0x25, 0x53, 0xff, 0x1c,
	0x9a, 0x0b, 0x73, 0x86, 0xd3, 0x07, 0xd0, 0xe0, 0x38, 0xa1, 0x2c, 0x62, 0xd1, 0x68, 0xa0, 0x0e,
	0x68, 0x7a, 0xdb, 0x8b, 0xd9, 0x5e, 0xe2, 0x23, 0x81, 0x72, 0x48, 0x25, 0x35, 0xd2, 0xab, 0xbe,
	0xfd, 0xbf, 0x1c, 0xd8, 0x3d, 0x15, 0x92, 0x5e, 0x8d, 0x99, 0xb8, 0xee, 0x4e, 0x1f, 0xbe, 0xdc,
	0xbe, 0x2e, 0x11, 0xc9, 0x93, 0x9a, 0xb2, 0x48, 0x8b, 0x93, 0xce, 0x46, 0x35, 0x99, 0x50, 0x1d,
	0x88, 0x0b, 0x95, 0x09, 0x7d, 0xc5, 0x26, 0xb3, 0x89, 0xca, 0x49, 0x39, 0x48, 0x87, 0xfe, 0x87,
	0xb0, 0x97, 0xa3, 0xbc, 0x36, 0x37, 0x7f, 0x3a, 0xd0, 0xfc, 0x8e, 0x45, 0xf2, 0x7f, 0xe5, 0xd9,
	0x3e, 0x3c, 0xa2, 0x93, 0xe9, 0x2c, 0x92, 0xc6, 0x31, 0x33, 0x4a, 0x1e, 0xcd, 0x92, 0xeb, 0x3a,
	0x97, 0x3a, 0xff, 0x54, 0xa0, 0x65, 0x64, 0xbe, 0xd7, 0xed, 0xeb, 0x7e, 0x8f, 0x5c, 0x40, 0x35,
	0x6d, 0x01, 0x48, 0xb6, 0x05, 0x29, 0x6c, 0x2f, 0xbc, 0xf7, 0x5e, 0xb3, 0xc3, 0xd8, 0x3d, 0x87,
	0x7a, 0xa6, 0xf4, 0x93, 0x27, 0x99, 0x13, 0xab, 0xb2, 0xe2, 0xbd, 0xbb, 0x6e, 0xd9, 0xa0, 0x5d,
	0x42, 0xb3, 0xcb, 0x31, 0xed, 0x01, 0x54, 0x03, 0x77, 0x58, 0x70, 0x24, 0x2b, 0xad, 0x5e, 0x7b,
	0xfd, 0x06, 0x83, 0xda, 0x83, 0x66, 0x46, 0xc8, 0x15, 0x6a, 0x96, 0xe7, 0x6a, 0x0f, 0x61, 0xf1,
	0x2c, 0xea, 0x01, 0x7a, 0xd0, 0xcc, 0xc8, 0xec, 0x0a, 0xe2, 0x6a, 0x03, 0x60, 0x21, 0x16, 0x29,
	0xf4, 0x97, 0xf0, 0x48, 0xcb, 0x16, 0x71, 0x2d, 0x7f, 0x32, 0x1a, 0xe9, 0x1d, 0x14, 0xac, 0x98,
	0xe3, 0x17, 0xb0, 0x95, 0x15, 0x23, 0x92, 0x35, 0x57, 0x20, 0x75, 0xde, 0xe1, 0xda, 0x75, 0x03,
	0xd8, 0x85, 0x6a, 0xaa, 0x33, 0xc4, 0xcb, 0x6d, 0xce, 0xa8, 0x97, 0xf7, 0xb8, 0x70, 0x6d, 0x09,
	0x92, 0x56, 0x77, 0x0b, 0x24, 0xa7, 0x47, 0x16, 0xc8, 0x8a, 0x1c, 0x7c, 0x0d, 0x15, 0x53, 0x5b,
	0xc9, 0x81, 0xbd, 0x2f, 0xa3, 0x07, 0x9e, 0x57, 0xb4, 0xb4, 0x44, 0x30, 0x95, 0xd0, 0x42, 0xb0,
	0x8b, 0xb1, 0x85, 0x90, 0x2f, 0x9c, 0x01, 0x6c, 0x5b, 0x95, 0xc4, 0xba, 0x95, 0x45, 0x65, 0xd1,
	0xba, 0x95, 0xc5, 0x45, 0xa8, 0x0b, 0xd5, 0xf4, 0x15, 0x5b, 0xc1, 0xc9, 0x95, 0x21, 0x2b, 0x38,
	0xf9, 0x67, 0xff, 0x7c, 0xf3, 0xa7, 0x12, 0x8f, 0x87, 0x57, 0x8f, 0xd4, 0x7f, 0xdc, 0xb3, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x95, 0x86, 0x6b, 0xd8, 0x0d, 0x00, 0x00,
}
