// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nodestore/nodestore.proto

package nodestore // import "github.com/quorumcontrol/tupelo/rpcserver/nodestore"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import rpcserver "github.com/quorumcontrol/tupelo/rpcserver"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRequest struct {
	Cid                  *rpcserver.Cid `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodestore_7c8e0a8727ae87df, []int{0}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetCid() *rpcserver.Cid {
	if m != nil {
		return m.Cid
	}
	return nil
}

type GetResponse struct {
	Node                 *rpcserver.Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodestore_7c8e0a8727ae87df, []int{1}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetNode() *rpcserver.Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type PutRequest struct {
	Node                 *rpcserver.Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodestore_7c8e0a8727ae87df, []int{2}
}
func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (dst *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(dst, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetNode() *rpcserver.Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type PutResponse struct {
	Cid                  *rpcserver.Cid `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodestore_7c8e0a8727ae87df, []int{3}
}
func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (dst *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(dst, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func (m *PutResponse) GetCid() *rpcserver.Cid {
	if m != nil {
		return m.Cid
	}
	return nil
}

type DeleteRequest struct {
	Cid                  *rpcserver.Cid `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodestore_7c8e0a8727ae87df, []int{4}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetCid() *rpcserver.Cid {
	if m != nil {
		return m.Cid
	}
	return nil
}

type ConfirmationResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmationResponse) Reset()         { *m = ConfirmationResponse{} }
func (m *ConfirmationResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmationResponse) ProtoMessage()    {}
func (*ConfirmationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodestore_7c8e0a8727ae87df, []int{5}
}
func (m *ConfirmationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmationResponse.Unmarshal(m, b)
}
func (m *ConfirmationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmationResponse.Marshal(b, m, deterministic)
}
func (dst *ConfirmationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmationResponse.Merge(dst, src)
}
func (m *ConfirmationResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmationResponse.Size(m)
}
func (m *ConfirmationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmationResponse proto.InternalMessageInfo

func (m *ConfirmationResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "tupelo.nodestore.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "tupelo.nodestore.GetResponse")
	proto.RegisterType((*PutRequest)(nil), "tupelo.nodestore.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "tupelo.nodestore.PutResponse")
	proto.RegisterType((*DeleteRequest)(nil), "tupelo.nodestore.DeleteRequest")
	proto.RegisterType((*ConfirmationResponse)(nil), "tupelo.nodestore.ConfirmationResponse")
}

func init() {
	proto.RegisterFile("nodestore/nodestore.proto", fileDescriptor_nodestore_7c8e0a8727ae87df)
}

var fileDescriptor_nodestore_7c8e0a8727ae87df = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x29, 0x8a, 0xca, 0x6c, 0x05, 0x59, 0x3c, 0x54, 0x41, 0x28, 0x7b, 0x12, 0x94, 0x44,
	0x2c, 0xfe, 0x01, 0x2b, 0x78, 0x13, 0xd9, 0xa3, 0x37, 0x9b, 0x1d, 0x35, 0xb0, 0x9b, 0xd9, 0xce,
	0x4c, 0xfc, 0xfd, 0xd2, 0x98, 0xc6, 0xe3, 0x7a, 0x4b, 0xde, 0x7c, 0xf3, 0xe6, 0xf1, 0xe0, 0x22,
	0x50, 0x87, 0xa2, 0xc4, 0x68, 0xcb, 0xcb, 0x8c, 0x4c, 0x4a, 0xf5, 0x99, 0xc6, 0x11, 0x7b, 0x32,
	0x45, 0xbf, 0x9c, 0x67, 0x25, 0xcd, 0x9b, 0x1b, 0x80, 0x67, 0xd4, 0x16, 0xb7, 0x11, 0x45, 0xeb,
	0x2b, 0x38, 0x70, 0xbe, 0x5b, 0xcc, 0x96, 0xb3, 0xeb, 0xea, 0xbe, 0x32, 0x99, 0x5c, 0xfb, 0xae,
	0xdd, 0xe9, 0x8d, 0x85, 0x2a, 0xc1, 0x32, 0x52, 0x10, 0xac, 0x97, 0x70, 0xb8, 0xb3, 0xcd, 0xf8,
	0x7c, 0x8f, 0xbf, 0x50, 0x87, 0x6d, 0x9a, 0x34, 0x06, 0xe0, 0x35, 0x16, 0xf7, 0x69, 0xfe, 0x16,
	0xaa, 0xc4, 0xe7, 0x03, 0x13, 0x71, 0x0c, 0x9c, 0x3e, 0x61, 0x8f, 0x8a, 0xff, 0x8c, 0x7f, 0x07,
	0xe7, 0x6b, 0x0a, 0x1f, 0x9e, 0x87, 0x77, 0xf5, 0x14, 0xca, 0x99, 0x05, 0x1c, 0x4b, 0x74, 0x0e,
	0x45, 0xd2, 0xea, 0x49, 0xbb, 0xff, 0x3e, 0x3e, 0xbc, 0xad, 0x3e, 0xbd, 0x7e, 0xc5, 0x8d, 0x71,
	0x34, 0xd8, 0x6d, 0x24, 0x8e, 0x83, 0xa3, 0xa0, 0x4c, 0xbd, 0xfd, 0x75, 0xb7, 0x3c, 0x3a, 0x41,
	0xfe, 0x46, 0xfe, 0xab, 0x7e, 0x73, 0x94, 0xba, 0x5d, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x5c,
	0x4e, 0x1d, 0x53, 0x98, 0x01, 0x00, 0x00,
}
