input ResolveInput {
	did: ID!
	path: String
}

type ResolvePayload {
	Nodes: [String!] # base64 encoded nodes
	Remaining: [String]
    Tip: String
}

type Query {
	resolve(input: ResolveInput!):ResolvePayload
}