Namespace = ""
NotaryGroupConfig = "../perfgroup.toml"
PublicIP = ""
Port = 0
WebSocketPort = 0
SecureWebSocketDomain = ""
CertificateCache = ""
BootstrapOnly = false
TracingSystem = ""

[Storage]
  Kind = ""
  Path = ""
  CacheSize = 0
  RegionEndpoint = ""
  Bucket = ""
  Region = ""
  AccessKey = ""
  SecretKey = ""
  LocalS3 = false
  RootDirectory = ""

[PrivateKeySet]
  SignKeyHex = "0x56530745c6e6dd39f8906f7434377ccd8e9baa170699815b970f12fa838b5650"
  DestKeyHex = "0x967ea91a965db2b93e6d508b3c0ac6f92e2e5807b747bfa12aee677053241a5c"
