Namespace = ""
NotaryGroupConfig = "../perfgroup.toml"
Gossip3NotaryGroupConfig = ""
PublicIP = ""
Port = 0
WebSocketPort = 0
SecureWebSocketDomain = ""
CertificateCache = ""
BootstrapOnly = false
TracingSystem = ""

[Storage]
  Kind = ""
  Path = ""
  CacheSize = 0
  RegionEndpoint = ""
  Bucket = ""
  Region = ""
  AccessKey = ""
  SecretKey = ""
  LocalS3 = false
  RootDirectory = ""

[PrivateKeySet]
  SignKeyHex = "0x46be753ee564fa42e9e3c3a7c0a7fd8cea457592c6987441d3550fe005c260fb"
  DestKeyHex = "0x54c3ec5b5e5cfedc73437e8eba0738040f13ee7cfeb05673dd89952d6669ee31"
