Namespace = ""
NotaryGroupConfig = "../perfgroup.toml"
Gossip3NotaryGroupConfig = ""
PublicIP = ""
Port = 0
WebSocketPort = 0
SecureWebSocketDomain = ""
CertificateCache = ""
BootstrapOnly = false
TracingSystem = ""

[Storage]
  Kind = ""
  Path = ""
  CacheSize = 0
  RegionEndpoint = ""
  Bucket = ""
  Region = ""
  AccessKey = ""
  SecretKey = ""
  LocalS3 = false
  RootDirectory = ""

[PrivateKeySet]
  SignKeyHex = "0x6ba60367b6d97174a7b32426f691870ec6cf67123811dee622281d09826a2077"
  DestKeyHex = "0x0687ecf7d66b973dc54481f92a6c24bf17356b6cd5a849dc21f6b237bc9f61c9"
