#!/usr/bin/env bash

TARGET_DIR="/go/src/github.com/quorumcontrol/tupelo/"
IMAGE_AND_TAG="tupelo:latest"
HOSTS=("debian@51.15.114.122" "debian@51.15.78.52" "debian@51.15.45.207")

pushd `dirname $0`/../
trap popd EXIT

docker build --tag $IMAGE_AND_TAG .
docker save -o .storage/dockerimage.tar tupelo:latest

remoteCmds() {
  local HOST=$1
  ssh $HOST "mkdir -p $TARGET_DIR"
  scp .storage/dockerimage.tar $HOST:$TARGET_DIR/
  ssh $HOST "cd $TARGET_DIR && docker load -i dockerimage.tar && rm -f dockerimage.tar"
  scp docker-compose-testnetwork.yml $HOST:$TARGET_DIR/docker-compose.yml
}

for h in "${HOSTS[@]}"; do
  remoteCmds "$h" &
done

wait

rm -f .storage/dockerimage.tar
