#!/usr/bin/env bash

set -e

pushd $(dirname $0)/../
trap popd EXIT

projectdir=$(pwd)
bindir=${projectdir}/bin/
releasedir=${projectdir}/release/
version=$1

if [ -z "$version" ]; then
  echo "Specify version (v#.#.#) as first argument"
  exit 1
fi

linux_binary="tupelo-${version}-linux-amd64"
macos_binary="tupelo-${version}-darwin-amd64"
windows_binary="tupelo-${version}-windows-amd64.exe"

./build

if [ -z "${LOCAL}" ]; then
  echo "Tagging ${version} and pushing to GitHub"
  git tag ${version}
  git push origin ${version}
fi

generateSha256 ${linux_binary}
generateSha256 ${macos_binary}
# generateSha256 ${windows_binary}

cd $(dirname $bindir)
zip $releasedir/tupelo-$version.zip -r $(basename $bindir)

generateSha256() {
  filename=$1
  if ! [ -x "$(command -v docker)" ]; then
    echo "docker is not installed, can't generate sha256"
  else
    container_id=$(docker run -d --entrypoint=tail alpine -f /dev/null)
    docker cp $bindir/$filename $container_id:$filename
    sha256=$(docker exec $container_id sha256sum $filename)
    echo $sha256 >> $releasedir/tupelo-${version}-checksums.txt
  fi
}
