name: Test suite

on: [push]

jobs:
  test:
    name: "run test suite"
    runs-on: ubuntu-latest
    env:
      # ${{ runner.workspace }} is not available here, so hardcode for now
      # setup-go is considering inject these env vars automatically
      GOPATH: /home/runner/work/tupelo/go
      GOBIN: /home/runner/work/tupelo/go/bin
    steps:
    - name: install go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler make
    - uses: actions/checkout@v1
    - name: git setup
      run: scripts/ci-gitsetup.sh
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: run tests
      run: scripts/test-suite.sh
